Update to newer version of pybind11 to fix compile error (#406)
Fix the "error C2027: use of undefined type '_frame'" by update to pybind11 v2.10.

Use CMAKE_CXX_STANDARD to fix CMake error "PYBIND11_CPP_STANDARD should be replaced with CMAKE_CXX_STANDARD" after update pybind11.